<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { BookUser, KeyRound, ShieldCheck, Sparkles, UserRound, X } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { ApiError, authApi } from '@/api/client'
import AcademicPortraitForm from '@/components/AcademicPortraitForm.vue'
import AiQuotaSummary from '@/components/AiQuotaSummary.vue'
import DashboardLayout from '@/components/DashboardLayout.vue'
import MentorStorageQuotaSummary from '@/components/MentorStorageQuotaSummary.vue'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAuthStore } from '@/stores/auth'
import type { MentorAcademicProfile, Role, StudentAcademicProfile } from '@/types/auth'

type Panel = 'password' | 'portrait' | 'quota' | null
const auth = useAuthStore(); const { t } = useI18n(); const route = useRoute(); const router = useRouter()
const role = computed<Role>(() => auth.state.user?.roles.some(role => ['admin', 'super_admin', 'institution_admin'].includes(role)) ? 'admin' : auth.state.user?.roles.includes('mentor') ? 'mentor' : 'student')
const hasPortrait = computed(() => role.value !== 'admin'); const activePanel = ref<Panel>(null)
const profile = ref<StudentAcademicProfile | MentorAcademicProfile | null>(null); const currentPassword = ref(''); const newPassword = ref(''); const confirmation = ref('')
const loadingProfile = ref(false); const savingProfile = ref(false); const changingPassword = ref(false); const notice = ref(''); const error = ref('')
function openPanel(panel: Exclude<Panel, null>) { activePanel.value = panel; router.replace({ query: { ...route.query, panel } }) }
function closePanel() { activePanel.value = null; const query = { ...route.query }; delete query.panel; router.replace({ query }) }
watch(() => route.query.panel, (panel) => { activePanel.value = panel === 'password' || panel === 'portrait' || panel === 'quota' ? panel : null }, { immediate: true })
async function loadProfile() { if (!auth.state.token || !hasPortrait.value) return; loadingProfile.value = true; try { profile.value = (role.value === 'student' ? await authApi.studentProfile(auth.state.token) : await authApi.mentorProfile(auth.state.token)).data } catch { error.value = t('updateFailed') } finally { loadingProfile.value = false } }
async function saveProfile(payload: StudentAcademicProfile | MentorAcademicProfile) { if (!auth.state.token) return; savingProfile.value = true; error.value = ''; try { profile.value = (role.value === 'student' ? await authApi.updateStudentProfile(auth.state.token, payload as StudentAcademicProfile) : await authApi.updateMentorProfile(auth.state.token, payload as MentorAcademicProfile)).data; notice.value = t('portraitSaved'); closePanel() } catch { error.value = t('updateFailed') } finally { savingProfile.value = false } }
async function changePassword() { if (!auth.state.token) return; error.value = ''; if (newPassword.value !== confirmation.value) { error.value = t('passwordMismatch'); return }; changingPassword.value = true; try { await auth.changePassword(currentPassword.value, newPassword.value); currentPassword.value = ''; newPassword.value = ''; confirmation.value = ''; notice.value = t('passwordChanged'); closePanel() } catch (exception) { error.value = exception instanceof ApiError && exception.code === 'current_password_incorrect' ? t('currentPasswordIncorrect') : t('updateFailed') } finally { changingPassword.value = false } }
onMounted(loadProfile)
</script>

<template>
  <DashboardLayout><div class="mx-auto w-full max-w-6xl"><div class="flex items-start gap-4"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-slate-900 text-white"><UserRound class="h-6 w-6" /></span><div><p class="text-sm font-medium text-sky-700">{{ auth.state.user?.username }}</p><h1 class="mt-1 text-3xl font-semibold tracking-tight text-slate-900">{{ t('accountManagement') }}</h1><p class="mt-2 leading-7 text-slate-600">{{ t('accountManagementDescription') }}</p></div></div>
    <Card class="mt-8 p-6"><div class="flex items-center gap-2"><ShieldCheck class="h-5 w-5 text-sky-700" /><h2 class="font-semibold text-slate-900">{{ t('accountSettings') }}</h2></div><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-slate-500">{{ t('fullName') }}</dt><dd class="mt-1 font-medium">{{ auth.state.user?.full_name }}</dd></div><div><dt class="text-slate-500">{{ t('accountName') }}</dt><dd class="mt-1 font-medium">{{ auth.state.user?.username }}</dd></div><div><dt class="text-slate-500">{{ t('selectIdentity') }}</dt><dd class="mt-1 font-medium">{{ t(role) }}</dd></div><div><dt class="text-slate-500">{{ t('language') }}</dt><dd class="mt-1 font-medium">{{ auth.state.user?.preferred_locale === 'zh-CN' ? t('languageChinese') : t('languageEnglish') }}</dd></div></dl></Card>
    <div class="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><button type="button" class="rounded-2xl border border-slate-200 bg-white p-6 text-left transition hover:border-sky-300 hover:shadow-sm" @click="openPanel('password')"><KeyRound class="h-6 w-6 text-sky-700" /><h2 class="mt-4 font-semibold">{{ t('changePassword') }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ t('passwordHint') }}</p></button><button v-if="hasPortrait" type="button" class="rounded-2xl border border-slate-200 bg-white p-6 text-left transition hover:border-sky-300 hover:shadow-sm" @click="openPanel('portrait')"><BookUser class="h-6 w-6 text-sky-700" /><h2 class="mt-4 font-semibold">{{ t('managePortrait') }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ t('academicPortrait') }}</p></button><button v-if="hasPortrait" type="button" class="rounded-2xl border border-slate-200 bg-white p-6 text-left transition hover:border-sky-300 hover:shadow-sm" @click="openPanel('quota')"><Sparkles class="h-6 w-6 text-sky-700" /><h2 class="mt-4 font-semibold">{{ t('personalQuota') }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ t('aiQuotaNote') }}</p></button><MentorStorageQuotaSummary v-if="role === 'mentor'" /></div>
    <p v-if="notice" class="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ notice }}</p><p v-if="error" class="mt-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{{ error }}</p>
    <div v-if="activePanel" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" @click.self="closePanel"><Card class="max-h-[90vh] w-full max-w-3xl overflow-y-auto p-6"><div class="flex items-center justify-between gap-4"><h2 class="text-xl font-semibold">{{ activePanel === 'password' ? t('changePassword') : activePanel === 'portrait' ? t('managePortrait') : t('personalQuota') }}</h2><Button variant="ghost" size="icon" @click="closePanel"><X class="h-4 w-4" /></Button></div><form v-if="activePanel === 'password'" class="mt-6 grid gap-4" @submit.prevent="changePassword"><label class="grid gap-1.5 text-sm font-medium">{{ t('currentPassword') }}<Input v-model="currentPassword" type="password" autocomplete="current-password" required /></label><label class="grid gap-1.5 text-sm font-medium">{{ t('newPassword') }}<Input v-model="newPassword" type="password" minlength="12" autocomplete="new-password" required /></label><label class="grid gap-1.5 text-sm font-medium">{{ t('confirmPassword') }}<Input v-model="confirmation" type="password" minlength="12" autocomplete="new-password" required /></label><Button class="w-fit" type="submit" :disabled="changingPassword">{{ changingPassword ? t('loading') : t('changePassword') }}</Button></form><div v-else-if="activePanel === 'portrait'"><div v-if="loadingProfile" class="py-10 text-sm text-slate-500">{{ t('loading') }}</div><AcademicPortraitForm v-else-if="profile" class="mt-6" :role="role as 'student' | 'mentor'" :initial-value="profile" :submitting="savingProfile" :submit-label="t('save')" @submit="saveProfile" /></div><AiQuotaSummary v-else class="mt-6" /></Card></div>
  </div></DashboardLayout>
</template>
