<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Search, Settings2, Unlock, UsersRound } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import { authApi } from '@/api/client'
import DashboardLayout from '@/components/DashboardLayout.vue'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAuthStore } from '@/stores/auth'
import type { AdminSelectionRecord, AdminSelectionUser, SelectionStatus } from '@/types/auth'

const auth = useAuthStore(); const { t } = useI18n()
const role = ref<'student' | 'mentor'>('student')
const isOpen = ref(true); const capacity = ref(5); const choiceLimit = ref(1)
const users = ref<AdminSelectionUser[]>([]); const records = ref<AdminSelectionRecord[]>([])
const recordIds = ref<string[]>([]); const recordStatus = ref<SelectionStatus | ''>(''); const recordSearch = ref('')
const loading = ref(false); const message = ref(''); const error = ref('')
const specialUsers = computed(() => users.value.filter((item) => item.is_exempt || (item.role === 'student' ? item.choice_limit !== null : item.capacity !== null)))
const statusLabels: Record<SelectionStatus, string> = { pending_student: 'selectedPending', pending_mentor: 'mentorInvitationPending', confirmed: 'selectionConfirmed', rejected: 'rejected', cancelled: 'cancelled' }
const statuses = Object.keys(statusLabels) as SelectionStatus[]

async function loadSettings() { if (!auth.state.token) return; const settings = await authApi.selectionSettings(auth.state.token); isOpen.value = settings.is_open; capacity.value = settings.default_capacity; choiceLimit.value = settings.default_student_choice_limit }
async function loadUsers() { if (!auth.state.token) return; users.value = await authApi.adminSelectionUsers(auth.state.token, role.value) }
async function loadRecords() { if (!auth.state.token) return; const result = await authApi.adminSelectionRecords(auth.state.token, { selection_status: recordStatus.value || undefined, search: recordSearch.value.trim() || undefined }); records.value = result.items; recordIds.value = recordIds.value.filter((id) => result.items.some((item) => item.id === id)) }
async function load() { loading.value = true; error.value = ''; try { await Promise.all([loadSettings(), loadUsers(), loadRecords()]) } catch { error.value = t('updateFailed') } finally { loading.value = false } }
async function saveGlobal() { if (!auth.state.token) return; loading.value = true; try { await authApi.updateSelectionSettings(auth.state.token, { is_open: isOpen.value, default_capacity: capacity.value, default_student_choice_limit: choiceLimit.value }); message.value = t('selectionUpdated') } catch { error.value = t('updateFailed') } finally { loading.value = false } }
async function saveUser(user: AdminSelectionUser, useDefault = false) { if (!auth.state.token) return; loading.value = true; try { const result = await authApi.updateAdminSelectionUser(auth.state.token, user.user_id, useDefault ? { use_default: true } : user.role === 'student' ? { choice_limit: user.choice_limit || undefined, is_exempt: user.is_exempt } : { capacity: user.capacity || undefined, is_exempt: user.is_exempt, selection_mode: user.selection_mode || undefined }); users.value = users.value.map((item) => item.user_id === result.user_id ? result : item); message.value = t('selectionUpdated') } catch { error.value = t('updateFailed') } finally { loading.value = false } }
async function releaseRecords(ids: string[]) {
  if (!auth.state.token || !ids.length) return
  const firstId = ids[0]
  if (!firstId || !window.confirm(`${t('releaseSelected')} (${ids.length})?`)) return
  loading.value = true
  try {
    if (ids.length === 1) await authApi.releaseAdminSelectionRecord(auth.state.token, firstId)
    else await authApi.releaseAdminSelectionRecords(auth.state.token, ids)
    recordIds.value = []
    await Promise.all([loadRecords(), loadUsers()])
    message.value = t('selectionUpdated')
  } catch { error.value = t('updateFailed') } finally { loading.value = false }
}
function switchRole(value: 'student' | 'mentor') { role.value = value; void loadUsers() }
onMounted(load)
</script>

<template>
  <DashboardLayout><div class="mx-auto w-full max-w-7xl"><p class="text-sm font-medium text-sky-700">{{ t('workspace') }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-slate-900">{{ t('selectionManagement') }}</h1><p class="mt-3 leading-7 text-slate-600">{{ t('selectionIntro') }}</p>
    <Card class="mt-8 p-6"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-slate-900 text-white"><Settings2 class="h-5 w-5" /></span><div><h2 class="font-semibold">{{ t('selectionManagement') }}</h2><p class="text-sm text-slate-500">{{ t('selectionCapacity') }}</p></div></div><div class="mt-7 grid gap-5 md:grid-cols-3"><label class="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><input v-model="isOpen" type="checkbox" class="h-4 w-4" /><span class="font-medium">{{ t('selectionOpen') }}</span></label><label class="grid gap-2 text-sm font-medium"><span>{{ t('defaultMentorCapacity') }}</span><Input :model-value="String(capacity)" type="number" min="1" max="200" @update:model-value="capacity = Number($event)" /></label><label class="grid gap-2 text-sm font-medium"><span>{{ t('studentChoiceLimit') }}</span><Input :model-value="String(choiceLimit)" type="number" min="1" max="50" @update:model-value="choiceLimit = Number($event)" /></label></div><Button class="mt-6" :disabled="loading" @click="saveGlobal">{{ t('saveSelectionSettings') }}</Button></Card>
    <Card class="mt-6 overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div class="flex items-center gap-2"><UsersRound class="h-5 w-5 text-sky-700" /><h2 class="font-semibold">{{ t('selectionManagement') }}</h2></div><div class="flex rounded-lg bg-slate-100 p-1"><button v-for="item in ['student', 'mentor'] as const" :key="item" class="rounded-md px-3 py-1.5 text-sm" :class="role === item ? 'bg-white font-medium shadow-sm' : 'text-slate-500'" @click="switchRole(item)">{{ t(item) }}</button></div></div><div v-if="loading" class="p-6 text-sm text-slate-500">{{ t('loading') }}</div><div v-else class="divide-y divide-slate-100"><div v-for="user in users" :key="user.user_id" class="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_12rem_10rem_auto]"><div class="min-w-0"><p class="font-medium">{{ user.full_name }} <span v-if="user.is_exempt" class="ml-2 rounded-full bg-violet-100 px-2 py-1 text-xs text-violet-800">{{ t('exceptionEnabled') }}</span></p><p class="mt-1 truncate text-sm text-slate-500">{{ user.username }} · {{ user.institution_name_zh }} · {{ user.college_name_zh }}</p></div><label class="flex items-center gap-2 text-sm"><input v-model="user.is_exempt" type="checkbox" class="h-4 w-4" />{{ t('exceptionEnabled') }}</label><Input v-if="role === 'student'" :model-value="user.choice_limit === null ? '' : String(user.choice_limit)" :placeholder="t('studentChoiceLimit')" type="number" min="1" max="50" @update:model-value="user.choice_limit = $event ? Number($event) : null" /><Input v-else :model-value="user.capacity === null ? '' : String(user.capacity)" :placeholder="t('selectionCapacity')" type="number" min="1" max="200" @update:model-value="user.capacity = $event ? Number($event) : null" /><div class="flex flex-wrap gap-2"><Button variant="outline" :disabled="loading" @click="saveUser(user)">{{ t('save') }}</Button><Button v-if="user.is_exempt || (role === 'student' ? user.choice_limit !== null : user.capacity !== null)" variant="ghost" :disabled="loading" @click="saveUser(user, true)">{{ t('standardRule') }}</Button></div></div><p v-if="!users.length" class="p-8 text-center text-sm text-slate-500">{{ t('noUsers') }}</p></div></Card>
    <Card v-if="specialUsers.length" class="mt-6 p-5"><h2 class="font-semibold">{{ t('exceptionEnabled') }}</h2><p class="mt-3 text-sm text-slate-600">{{ specialUsers.map((item) => item.full_name).join(' · ') }}</p></Card>
    <Card class="mt-6 overflow-hidden"><div class="flex flex-col justify-between gap-4 border-b border-slate-200 p-5 lg:flex-row lg:items-center"><div class="flex items-center gap-2"><Unlock class="h-5 w-5 text-sky-700" /><h2 class="font-semibold">{{ t('selectionRecords') }}</h2></div><Button v-if="recordIds.length" variant="outline" :disabled="loading" @click="releaseRecords(recordIds)">{{ t('releaseSelected') }} ({{ recordIds.length }})</Button></div><form class="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-[minmax(0,1fr)_12rem_auto]" @submit.prevent="loadRecords"><label class="relative"><Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input v-model="recordSearch" class="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-sky-500" :placeholder="t('searchUsersPlaceholder')" /></label><select v-model="recordStatus" class="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">{{ t('all') }}</option><option v-for="item in Object.keys(statusLabels) as SelectionStatus[]" :key="item" :value="item">{{ t(statusLabels[item]) }}</option></select><Button type="submit" variant="outline">{{ t('search') }}</Button></form><div v-if="loading" class="p-8 text-center text-sm text-slate-500">{{ t('loading') }}</div><div v-else-if="!records.length" class="p-8 text-center text-sm text-slate-500">{{ t('selectionActivityEmpty') }}</div><div v-else class="divide-y divide-slate-100"><div v-for="record in records" :key="record.id" class="grid gap-3 p-5 md:grid-cols-[auto_minmax(0,1fr)_auto]"><input v-model="recordIds" :value="record.id" type="checkbox" class="mt-1 h-4 w-4" /><div class="min-w-0"><p class="font-medium text-slate-900">{{ record.student_name }} <span class="text-slate-400">→</span> {{ record.mentor_name }} <span class="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-700">{{ t(statusLabels[record.status]) }}</span></p><p class="mt-1 truncate text-sm text-slate-500">{{ record.student_username }} · {{ record.student_institution_name_zh }} · {{ record.student_college_name_zh }}</p><p class="mt-1 truncate text-sm text-slate-500">{{ record.mentor_username }} · {{ record.mentor_institution_name_zh }} · {{ record.mentor_college_name_zh }}</p></div><Button size="sm" variant="ghost" :disabled="loading" @click="releaseRecords([record.id])">{{ t('releaseSelection') }}</Button></div></div></Card><p v-if="message" class="mt-5 text-sm text-emerald-700">{{ message }}</p><p v-if="error" class="mt-5 text-sm text-rose-700">{{ error }}</p>
  </div></DashboardLayout>
</template>
