<script setup lang="ts">
import { computed, onMounted, ref, type Component } from 'vue'
import { BellRing, BookOpenCheck, BotMessageSquare, CheckCircle2, Clock3, Database, GraduationCap, HardDrive, Sparkles, UsersRound } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import { authApi } from '@/api/client'
import DashboardLayout from '@/components/DashboardLayout.vue'
import ResourceRecommendationPanel from '@/components/ResourceRecommendationPanel.vue'
import { Card } from '@/components/ui/card'
import { useAuthStore } from '@/stores/auth'
import type { DashboardBreakdown, DashboardMetric, DashboardOverview, Role } from '@/types/auth'

const { t } = useI18n(); const auth = useAuthStore()
const activeRole = computed<Role>(() => auth.state.user?.roles.includes('admin') ? 'admin' : auth.state.user?.roles.includes('mentor') ? 'mentor' : 'student')
const data = ref<DashboardOverview | null>(null); const loading = ref(false); const error = ref('')
const metricLabels: Record<string, string> = { students_total: 'studentsTotal', mentors_total: 'mentorsTotal', preregistrations_pending: 'preregistrationsPending', resources_total: 'resourcesTotal', ai_project_calls: 'aiProjectCalls', mentor_matches_available: 'mentorMatchesAvailable', student_candidates_available: 'studentCandidatesAvailable', resources_owned: 'resourcesOwned', resource_storage: 'resourceStorage', ai_daily_calls: 'aiDailyCalls', ai_credit_balance: 'dashboardAiCreditBalance' }
const metricIcons: Record<string, Component> = { students_total: UsersRound, mentors_total: GraduationCap, preregistrations_pending: Database, resources_total: BookOpenCheck, ai_project_calls: BotMessageSquare, mentor_matches_available: Sparkles, student_candidates_available: UsersRound, resources_owned: BookOpenCheck, resource_storage: HardDrive, ai_daily_calls: BotMessageSquare, ai_credit_balance: Sparkles }
const selectionLabels: Record<string, string> = { pending_student: 'selectedPending', pending_mentor: 'mentorInvitationPending', confirmed: 'selectionConfirmed', rejected: 'rejected', cancelled: 'cancelled' }
const selectionMax = computed(() => Math.max(1, ...(data.value?.selection_statistics.map((item) => item.value) || [1])))
function displayMetric(metric: DashboardMetric) { if (metric.code === 'resource_storage') return `${(metric.value / 1024 / 1024).toFixed(1)} MB`; return metric.total !== null ? `${metric.value}/${metric.total}` : String(metric.value) }
function width(item: DashboardBreakdown) { return `${Math.max(item.value ? 8 : 0, item.value / selectionMax.value * 100)}%` }
function activityText(item: DashboardOverview['recent_selection_activity'][number]) { return `${item.student_name} · ${item.mentor_name}` }
function activityStatus(status: string) { return t(selectionLabels[status] || status) }
async function load() { if (!auth.state.token) return; loading.value = true; error.value = ''; try { data.value = await authApi.dashboard(auth.state.token) } catch { error.value = t('updateFailed') } finally { loading.value = false } }
onMounted(load)
</script>

<template>
  <DashboardLayout><div class="w-full"><div class="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p class="text-sm font-medium text-sky-700">{{ auth.state.user?.username }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-slate-900">{{ t('dashboardOverview') }}</h1></div><p class="text-sm text-slate-500">{{ auth.state.user?.full_name }} · {{ t(`${activeRole}Dashboard`) }}</p></div>
    <div v-if="loading" class="py-16 text-center text-sm text-slate-500">{{ t('loading') }}</div><template v-else-if="data"><div class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card v-for="metric in data.metrics" :key="metric.code" class="min-w-0 p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><p class="text-sm leading-5 text-slate-500">{{ t(metricLabels[metric.code] || metric.code) }}</p><component :is="metricIcons[metric.code] || Sparkles" class="h-4 w-4 shrink-0 text-sky-700" /></div><p class="mt-4 truncate text-2xl font-semibold tracking-tight text-slate-900">{{ displayMetric(metric) }}</p><div v-if="metric.total !== null" class="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-sky-600" :style="{ width: `${Math.min(100, metric.value / metric.total * 100)}%` }" /></div></Card></div>
      <div class="mt-6 grid gap-6 xl:grid-cols-2"><Card class="p-6 shadow-sm"><div class="flex items-center gap-2"><CheckCircle2 class="h-5 w-5 text-sky-700" /><h2 class="font-semibold text-slate-900">{{ t('selectionStatistics') }}</h2></div><div v-if="data.selection_statistics.length" class="mt-6 space-y-5"><div v-for="item in data.selection_statistics" :key="item.code"><div class="mb-2 flex justify-between text-sm"><span class="text-slate-600">{{ t(selectionLabels[item.code] || item.code) }}</span><span class="font-medium text-slate-900">{{ item.value }}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-sky-600" :style="{ width: width(item) }" /></div></div></div><p v-else class="mt-8 text-sm text-slate-500">{{ t('selectionActivityEmpty') }}</p></Card>
        <Card class="p-6 shadow-sm"><div class="flex items-center gap-2"><BellRing class="h-5 w-5 text-sky-700" /><h2 class="font-semibold text-slate-900">{{ t('latestSelectionMessages') }}</h2></div><div v-if="data.recent_selection_activity.length" class="mt-5 divide-y divide-slate-100"><div v-for="item in data.recent_selection_activity" :key="item.id" class="flex items-center justify-between gap-3 py-3"><div class="min-w-0"><p class="truncate text-sm font-medium text-slate-800">{{ activityText(item) }}</p><p class="mt-1 text-xs text-slate-500">{{ activityStatus(item.status) }}</p></div><Clock3 class="h-4 w-4 shrink-0 text-slate-400" /></div></div><p v-else class="mt-8 text-sm text-slate-500">{{ t('selectionActivityEmpty') }}</p></Card></div>
      <ResourceRecommendationPanel v-if="activeRole === 'student'" /><div v-else class="mt-7 grid gap-4 sm:grid-cols-2"><RouterLink :to="activeRole === 'mentor' ? '/mentor/resources' : '/admin/pre-registrations'" class="rounded-2xl border border-slate-200 bg-white p-6 transition hover:border-sky-200 hover:shadow-sm"><p class="text-sm font-medium text-sky-700">{{ activeRole === 'mentor' ? t('manageResources') : t('partnerPreRegistration') }}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ activeRole === 'mentor' ? t('resourceQuotaDescription') : t('templateDescription') }}</p></RouterLink><RouterLink :to="activeRole === 'mentor' ? '/mentor/matches' : '/admin/selection'" class="rounded-2xl border border-slate-200 bg-white p-6 transition hover:border-sky-200 hover:shadow-sm"><p class="text-sm font-medium text-sky-700">{{ t('mutualSelection') }}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ t('selectionIntro') }}</p></RouterLink></div>
    </template><p v-else-if="error" class="mt-8 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{{ error }}</p></div></DashboardLayout>
</template>
